# -*- coding: utf-8 -*-
"""build_index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLv4l0SgPlw1sIwLHK_zz3wY8EdUldOu
"""

import os, json, time
from datetime import datetime
import requests
import pandas as pd

BLS_ENDPOINT = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
API_KEY = os.getenv("BLS_API_KEY", "").strip()

BASE_DATE = "2021-01"
BENCHMARK_ID = "CUUR0000SA0"
OUTPUT_PATH = "data.json"

BASKET = [
    {"id": "WPU026301", "name": "Coffee (whole bean, ground, instant)", "weight": 0.35},
    {"id": "WPU0231",   "name": "Fluid milk products",                 "weight": 0.25},
    {"id": "WPU0253",   "name": "Refined sugar products",              "weight": 0.10},
    {"id": "WPU0542",   "name": "Commercial electric power",           "weight": 0.15},
    {"id": "WPU072A",   "name": "Plastic packaging products",          "weight": 0.15},
]

def fetch_bls(series_ids, start_year, end_year):
    payload = {
        "seriesid": series_ids,
        "startyear": str(start_year),
        "endyear": str(end_year),
        "annualaverage": False,
        "calculations": False,
        "registrationkey": API_KEY,
    }
    r = requests.post(
        BLS_ENDPOINT,
        data=json.dumps(payload),
        headers={"Content-type": "application/json"},
        timeout=30
    )
    r.raise_for_status()
    data = r.json()
    if data["status"] != "REQUEST_SUCCEEDED":
        raise RuntimeError(data["message"])
    return data

def parse_monthly(data):
    rows = []
    for s in data["Results"]["series"]:
        sid = s["seriesID"]
        for i in s["data"]:
            p = i["period"]
            if not p.startswith("M"):
                continue
            mm = p[1:]
            if not ("01" <= mm <= "12"):
                continue
            v = i["value"]
            if v == "-" or v == "":
                continue
            rows.append({
                "date": f"{i['year']}-{mm}",
                "series_id": sid,
                "value": float(v)
            })
    return pd.DataFrame(rows).pivot(index="date", columns="series_id", values="value").sort_index()

def main():
    now = datetime.now()
    start_year = now.year - 5
    end_year = now.year

    series_ids = [x["id"] for x in BASKET] + [BENCHMARK_ID]

    raw = fetch_bls(series_ids, start_year, end_year)
    df = parse_monthly(raw)

    if BASE_DATE not in df.index:
        raise RuntimeError("Base date missing")

    df = df[df.index >= BASE_DATE].dropna()
    base_vals = df.loc[BASE_DATE]
    df_norm = (df / base_vals) * 100.0

    df_norm["Cafe_Index"] = 0.0
    for b in BASKET:
        df_norm["Cafe_Index"] += df_norm[b["id"]] * b["weight"]

    latest_common = df_norm.index.max()

    output = {
        "labels": df_norm.index.tolist(),
        "cafe_index": df_norm["Cafe_Index"].round(1).tolist(),
        "cpi_index": df_norm[BENCHMARK_ID].round(1).tolist(),
        "series": BASKET,
        "meta": {
            "base_date": BASE_DATE,
            "latest_common_month": latest_common,
            "generated_at": datetime.now().isoformat()
        }
    }

    with open(OUTPUT_PATH, "w") as f:
        json.dump(output, f, indent=2)

    print("Wrote", OUTPUT_PATH)

if __name__ == "__main__":
    main()

