# -*- coding: utf-8 -*-
"""validate_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAi577f0S5ccVBShig23IP4uDNFZ6ibm
"""

import os, json, requests
from datetime import datetime

API_KEY = os.getenv("BLS_API_KEY", "").strip()
BLS_ENDPOINT = "https://api.bls.gov/publicAPI/v2/timeseries/data/"

SERIES = [
    "WPU026301",
    "WPU0231",
    "WPU0253",
    "WPU0542",
    "WPU072A",
    "CUUR0000SA0",
]

MAX_LAG_MONTHS = 3

def months_ago(yyyy_mm):
    y, m = map(int, yyyy_mm.split("-"))
    now = datetime.now()
    return (now.year - y) * 12 + (now.month - m)

payload = {
    "seriesid": SERIES,
    "startyear": str(datetime.now().year - 1),
    "endyear": str(datetime.now().year),
    "registrationkey": API_KEY
}

r = requests.post(
    BLS_ENDPOINT,
    data=json.dumps(payload),
    headers={"Content-type": "application/json"}
)
r.raise_for_status()
data = r.json()

if data["status"] != "REQUEST_SUCCEEDED":
    raise RuntimeError(data["message"])

ok = True

for s in data["Results"]["series"]:
    sid = s["seriesID"]
    valid = [i for i in s["data"] if i["period"].startswith("M") and i["value"] != "-"]
    if not valid:
        print("FAIL", sid, "no data")
        ok = False
        continue
    i = valid[0]
    last = f"{i['year']}-{i['period'][1:]}"
    if months_ago(last) > MAX_LAG_MONTHS:
        print("STALE", sid, last)
        ok = False
    else:
        print("OK", sid, last)

if not ok:
    raise SystemExit(1)

